[project]
name = "midterm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zaky Hafiedz", email = "zakyhafiedz10@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
]

[project.scripts]
midterm = "midterm:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
